// nvofg — resource registration and the AUTOMATIC-mode per-frame pipeline.
//
// Pipeline (ADR 0002, M1 forward-warp tier):
//   prep (luma)  ->  OFA execute (fwd flow + cost)  ->  refine (upsample, S10.5
//   decode, cost->confidence)  ->  warp (two-sided backward warp + anti-ghost).
// Three timeline-chained submits across the compute and optical-flow queues
// (ADR 0003 AUTOMATIC mode). Core Vulkan is called through the linked loader;
// the OFA entrypoints come from the app's loader (ctx->of).
#include "internal.hpp"

#include <cstring>
#include <vector>

// Embedded SPIR-V (generated by cmake/Shaders.cmake).
#include "nvofg_spv_prep.spv.h"
#include "nvofg_spv_refine.spv.h"
#include "nvofg_spv_warp.spv.h"

namespace {

uint32_t findMemoryType(VkPhysicalDevice pd, uint32_t bits, VkMemoryPropertyFlags props) {
    VkPhysicalDeviceMemoryProperties mp{};
    vkGetPhysicalDeviceMemoryProperties(pd, &mp);
    for (uint32_t i = 0; i < mp.memoryTypeCount; ++i)
        if ((bits & (1u << i)) && (mp.memoryTypes[i].propertyFlags & props) == props) return i;
    return UINT32_MAX;
}

bool createImage(NvofgContext* ctx, nvofg::Image& img, uint32_t w, uint32_t h, VkFormat fmt,
                 VkImageUsageFlags usage, VkOpticalFlowUsageFlagsNV ofUsage,
                 const uint32_t* families, uint32_t famCount) {
    img.format = fmt; img.w = w; img.h = h;

    VkOpticalFlowImageFormatInfoNV ofInfo{};
    ofInfo.sType = VK_STRUCTURE_TYPE_OPTICAL_FLOW_IMAGE_FORMAT_INFO_NV;
    ofInfo.usage = ofUsage;

    VkImageCreateInfo ici{};
    ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ici.pNext = ofUsage ? &ofInfo : nullptr;
    ici.imageType = VK_IMAGE_TYPE_2D;
    ici.format = fmt;
    ici.extent = {w, h, 1};
    ici.mipLevels = 1;
    ici.arrayLayers = 1;
    ici.samples = VK_SAMPLE_COUNT_1_BIT;
    ici.tiling = VK_IMAGE_TILING_OPTIMAL;
    ici.usage = usage;
    if (famCount > 1) {
        ici.sharingMode = VK_SHARING_MODE_CONCURRENT;
        ici.queueFamilyIndexCount = famCount;
        ici.pQueueFamilyIndices = families;
    } else {
        ici.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    }
    ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(ctx->device, &ici, nullptr, &img.image) != VK_SUCCESS) return false;

    VkMemoryRequirements req{};
    vkGetImageMemoryRequirements(ctx->device, img.image, &req);
    uint32_t mt = findMemoryType(ctx->physicalDevice, req.memoryTypeBits,
                                 VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (mt == UINT32_MAX) return false;
    VkMemoryAllocateInfo mai{};
    mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    mai.allocationSize = req.size;
    mai.memoryTypeIndex = mt;
    if (vkAllocateMemory(ctx->device, &mai, nullptr, &img.memory) != VK_SUCCESS) return false;
    if (vkBindImageMemory(ctx->device, img.image, img.memory, 0) != VK_SUCCESS) return false;

    VkImageViewCreateInfo vci{};
    vci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    vci.image = img.image;
    vci.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vci.format = fmt;
    vci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    return vkCreateImageView(ctx->device, &vci, nullptr, &img.view) == VK_SUCCESS;
}

bool createBuffer(NvofgContext* ctx, nvofg::Buffer& buf, VkDeviceSize size,
                  VkBufferUsageFlags usage) {
    buf.size = size;
    VkBufferCreateInfo bci{};
    bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bci.size = size;
    bci.usage = usage;
    bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(ctx->device, &bci, nullptr, &buf.buffer) != VK_SUCCESS) return false;
    VkMemoryRequirements req{};
    vkGetBufferMemoryRequirements(ctx->device, buf.buffer, &req);
    uint32_t mt = findMemoryType(ctx->physicalDevice, req.memoryTypeBits,
                                 VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (mt == UINT32_MAX) return false;
    VkMemoryAllocateInfo mai{};
    mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    mai.allocationSize = req.size;
    mai.memoryTypeIndex = mt;
    if (vkAllocateMemory(ctx->device, &mai, nullptr, &buf.memory) != VK_SUCCESS) return false;
    return vkBindBufferMemory(ctx->device, buf.buffer, buf.memory, 0) == VK_SUCCESS;
}

bool createStage(NvofgContext* ctx, nvofg::Stage& st, const void* spv, size_t spvSize,
                 const std::vector<VkDescriptorSetLayoutBinding>& bindings,
                 uint32_t pushSize) {
    VkShaderModuleCreateInfo smci{};
    smci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    smci.codeSize = spvSize;
    smci.pCode = reinterpret_cast<const uint32_t*>(spv);
    if (vkCreateShaderModule(ctx->device, &smci, nullptr, &st.module) != VK_SUCCESS) return false;

    VkDescriptorSetLayoutCreateInfo dlci{};
    dlci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    dlci.bindingCount = (uint32_t)bindings.size();
    dlci.pBindings = bindings.data();
    if (vkCreateDescriptorSetLayout(ctx->device, &dlci, nullptr, &st.setLayout) != VK_SUCCESS)
        return false;

    VkPushConstantRange pcr{VK_SHADER_STAGE_COMPUTE_BIT, 0, pushSize};
    VkPipelineLayoutCreateInfo plci{};
    plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    plci.setLayoutCount = 1;
    plci.pSetLayouts = &st.setLayout;
    if (pushSize) { plci.pushConstantRangeCount = 1; plci.pPushConstantRanges = &pcr; }
    if (vkCreatePipelineLayout(ctx->device, &plci, nullptr, &st.pipeLayout) != VK_SUCCESS)
        return false;

    VkComputePipelineCreateInfo cpci{};
    cpci.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cpci.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    cpci.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    cpci.stage.module = st.module;
    cpci.stage.pName = "main";
    cpci.layout = st.pipeLayout;
    return vkCreateComputePipelines(ctx->device, VK_NULL_HANDLE, 1, &cpci, nullptr, &st.pipeline)
           == VK_SUCCESS;
}

VkDescriptorSetLayoutBinding bind(uint32_t b, VkDescriptorType t) {
    return {b, t, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr};
}

}  // namespace

// ---------------------------------------------------------------------------
// Pipeline construction / teardown
// ---------------------------------------------------------------------------
namespace nvofg {

NvofgResult ensurePipeline(NvofgContext* ctx) {
    if (ctx->pipelineReady) return NVOFG_OK;
    if (!ctx->haveColor || !ctx->haveOutput) return NVOFG_NOT_REGISTERED;

    const uint32_t W = ctx->width, H = ctx->height;
    ctx->gridSize = 4;
    ctx->gridW = (W + ctx->gridSize - 1) / ctx->gridSize;
    ctx->gridH = (H + ctx->gridSize - 1) / ctx->gridSize;
    ctx->bidir = (ctx->flags & NVOFG_FLAG_BIDIRECTIONAL) && ctx->caps.bidirectional;
    const uint32_t fams[2] = {ctx->queueFamily, ctx->ofFamily};
    const uint32_t famCount = (ctx->queueFamily == ctx->ofFamily) ? 1 : 2;

    // --- scratch resources ---
    const VkImageUsageFlags kLumaUsage =
        VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
    if (!createImage(ctx, ctx->lumaPrev, W, H, VK_FORMAT_R8_UNORM, kLumaUsage,
                     VK_OPTICAL_FLOW_USAGE_INPUT_BIT_NV, fams, famCount) ||
        !createImage(ctx, ctx->lumaCurr, W, H, VK_FORMAT_R8_UNORM, kLumaUsage,
                     VK_OPTICAL_FLOW_USAGE_INPUT_BIT_NV, fams, famCount) ||
        // SAMPLED_BIT is required so a VkImageView can be created for OFA binding
        // (a view needs a view-compatible usage bit; TRANSFER_SRC alone is not).
        !createImage(ctx, ctx->flowImg, ctx->gridW, ctx->gridH, VK_FORMAT_R16G16_SFIXED5_NV,
                     VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
                     VK_OPTICAL_FLOW_USAGE_OUTPUT_BIT_NV, fams, famCount) ||
        !createImage(ctx, ctx->costImg, ctx->gridW, ctx->gridH, VK_FORMAT_R8_UINT,
                     VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
                     VK_OPTICAL_FLOW_USAGE_COST_BIT_NV, fams, famCount) ||
        !createImage(ctx, ctx->refinedFlow, W, H, VK_FORMAT_R16G16_SFLOAT,
                     VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT, 0, nullptr, 1) ||
        !createImage(ctx, ctx->refinedFlowBwd, W, H, VK_FORMAT_R16G16_SFLOAT,
                     VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT, 0, nullptr, 1) ||
        !createImage(ctx, ctx->confidence, W, H, VK_FORMAT_R8_UNORM,
                     VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT, 0, nullptr, 1) ||
        !createImage(ctx, ctx->occlusion, W, H, VK_FORMAT_R8_UNORM,
                     VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT, 0, nullptr, 1)) {
        ctx->setError("failed to allocate scratch images");
        return NVOFG_OUT_OF_MEMORY;
    }

    // Backward OFA outputs + copy buffers (only when bidirectional is enabled).
    if (ctx->bidir) {
        if (!createImage(ctx, ctx->flowBwdImg, ctx->gridW, ctx->gridH, VK_FORMAT_R16G16_SFIXED5_NV,
                         VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
                         VK_OPTICAL_FLOW_USAGE_OUTPUT_BIT_NV, fams, famCount) ||
            !createImage(ctx, ctx->costBwdImg, ctx->gridW, ctx->gridH, VK_FORMAT_R8_UINT,
                         VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
                         VK_OPTICAL_FLOW_USAGE_COST_BIT_NV, fams, famCount) ||
            !createBuffer(ctx, ctx->flowBwdBuf, (VkDeviceSize)ctx->gridW * ctx->gridH * 4,
                          VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT) ||
            !createBuffer(ctx, ctx->costBwdBuf, (VkDeviceSize)((ctx->gridW * ctx->gridH + 3) & ~3u),
                          VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT)) {
            ctx->setError("failed to allocate backward-flow resources");
            return NVOFG_OUT_OF_MEMORY;
        }
    }
    if (!createBuffer(ctx, ctx->flowBuf, (VkDeviceSize)ctx->gridW * ctx->gridH * 4,
                      VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT) ||
        !createBuffer(ctx, ctx->costBuf, (VkDeviceSize)((ctx->gridW * ctx->gridH + 3) & ~3u),
                      VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT)) {
        ctx->setError("failed to allocate flow/cost buffers");
        return NVOFG_OUT_OF_MEMORY;
    }

    // 1x1 fallback images bound where an aux/bidir input is absent.
    const VkImageUsageFlags kDummy = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
    if (!createImage(ctx, ctx->dummyR8, 1, 1, VK_FORMAT_R8_UNORM, kDummy, 0, nullptr, 1) ||
        !createImage(ctx, ctx->dummyRG16, 1, 1, VK_FORMAT_R16G16_SFLOAT, kDummy, 0, nullptr, 1)) {
        ctx->setError("failed to allocate dummy images");
        return NVOFG_OUT_OF_MEMORY;
    }

    // --- OFA session ---
    VkOpticalFlowSessionCreateInfoNV sci{};
    sci.sType = VK_STRUCTURE_TYPE_OPTICAL_FLOW_SESSION_CREATE_INFO_NV;
    sci.width = W; sci.height = H;
    sci.imageFormat = VK_FORMAT_R8_UNORM;
    sci.flowVectorFormat = VK_FORMAT_R16G16_SFIXED5_NV;
    sci.costFormat = VK_FORMAT_R8_UINT;
    sci.outputGridSize = VK_OPTICAL_FLOW_GRID_SIZE_4X4_BIT_NV;
    sci.hintGridSize = VK_OPTICAL_FLOW_GRID_SIZE_UNKNOWN_NV;
    sci.performanceLevel = (ctx->quality == NVOFG_QUALITY_HIGH) ? VK_OPTICAL_FLOW_PERFORMANCE_LEVEL_SLOW_NV
                        : (ctx->quality == NVOFG_QUALITY_PERF)  ? VK_OPTICAL_FLOW_PERFORMANCE_LEVEL_FAST_NV
                                                                : VK_OPTICAL_FLOW_PERFORMANCE_LEVEL_MEDIUM_NV;
    sci.flags = VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_COST_BIT_NV;
    if (ctx->bidir) sci.flags |= VK_OPTICAL_FLOW_SESSION_CREATE_BOTH_DIRECTIONS_BIT_NV;
    if (ctx->of.createSession(ctx->device, &sci, nullptr, &ctx->session) != VK_SUCCESS) {
        ctx->setError("vkCreateOpticalFlowSessionNV failed");
        return NVOFG_INTERNAL;
    }
    ctx->of.bindImage(ctx->device, ctx->session, VK_OPTICAL_FLOW_SESSION_BINDING_POINT_INPUT_NV,
                      ctx->lumaPrev.view, VK_IMAGE_LAYOUT_GENERAL);
    ctx->of.bindImage(ctx->device, ctx->session, VK_OPTICAL_FLOW_SESSION_BINDING_POINT_REFERENCE_NV,
                      ctx->lumaCurr.view, VK_IMAGE_LAYOUT_GENERAL);
    ctx->of.bindImage(ctx->device, ctx->session, VK_OPTICAL_FLOW_SESSION_BINDING_POINT_FLOW_VECTOR_NV,
                      ctx->flowImg.view, VK_IMAGE_LAYOUT_GENERAL);
    ctx->of.bindImage(ctx->device, ctx->session, VK_OPTICAL_FLOW_SESSION_BINDING_POINT_COST_NV,
                      ctx->costImg.view, VK_IMAGE_LAYOUT_GENERAL);
    if (ctx->bidir) {
        ctx->of.bindImage(ctx->device, ctx->session, VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_FLOW_VECTOR_NV,
                          ctx->flowBwdImg.view, VK_IMAGE_LAYOUT_GENERAL);
        ctx->of.bindImage(ctx->device, ctx->session, VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_COST_NV,
                          ctx->costBwdImg.view, VK_IMAGE_LAYOUT_GENERAL);
    }

    // --- sampler ---
    VkSamplerCreateInfo smp{};
    smp.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
    smp.magFilter = smp.minFilter = VK_FILTER_LINEAR;
    smp.addressModeU = smp.addressModeV = smp.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    vkCreateSampler(ctx->device, &smp, nullptr, &ctx->linearSampler);

    // --- compute stages ---
    using B = VkDescriptorSetLayoutBinding;
    std::vector<B> prepB = {bind(0, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE),
                            bind(1, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE)};
    std::vector<B> refineB = {bind(0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER),
                             bind(1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER),
                             bind(2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER),
                             bind(3, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE),
                             bind(4, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE),
                             bind(5, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE),
                             bind(6, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE),
                             bind(7, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE)};
    std::vector<B> warpB;
    for (uint32_t i = 0; i <= 3; ++i) warpB.push_back(bind(i, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE));
    for (uint32_t i = 4; i <= 7; ++i) warpB.push_back(bind(i, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE));
    warpB.push_back(bind(8, VK_DESCRIPTOR_TYPE_SAMPLER));
    warpB.push_back(bind(9, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE));
    if (!createStage(ctx, ctx->prepStage, nvofg_spv_prep, nvofg_spv_prep_size, prepB, 0) ||
        !createStage(ctx, ctx->refineStage, nvofg_spv_refine, nvofg_spv_refine_size, refineB, 28) ||
        !createStage(ctx, ctx->warpStage, nvofg_spv_warp, nvofg_spv_warp_size, warpB, 16)) {
        ctx->setError("failed to create compute pipelines");
        return NVOFG_INTERNAL;
    }

    // --- descriptor pool + sets ---
    VkDescriptorPoolSize sizes[] = {
        {VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, 16},
        {VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, 8},
        {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 4},
        {VK_DESCRIPTOR_TYPE_SAMPLER, 2}};
    VkDescriptorPoolCreateInfo dpci{};
    dpci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    dpci.maxSets = 4;
    dpci.poolSizeCount = 4;
    dpci.pPoolSizes = sizes;
    if (vkCreateDescriptorPool(ctx->device, &dpci, nullptr, &ctx->descPool) != VK_SUCCESS)
        return NVOFG_INTERNAL;

    auto alloc = [&](VkDescriptorSetLayout l, VkDescriptorSet& s) {
        VkDescriptorSetAllocateInfo ai{};
        ai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
        ai.descriptorPool = ctx->descPool;
        ai.descriptorSetCount = 1;
        ai.pSetLayouts = &l;
        return vkAllocateDescriptorSets(ctx->device, &ai, &s) == VK_SUCCESS;
    };
    if (!alloc(ctx->prepStage.setLayout, ctx->prepPrevSet) ||
        !alloc(ctx->prepStage.setLayout, ctx->prepCurrSet) ||
        !alloc(ctx->refineStage.setLayout, ctx->refineSet) ||
        !alloc(ctx->warpStage.setLayout, ctx->warpSet))
        return NVOFG_INTERNAL;

    // --- command pools ---
    VkCommandPoolCreateInfo cpci{};
    cpci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
    cpci.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    cpci.queueFamilyIndex = ctx->queueFamily;
    vkCreateCommandPool(ctx->device, &cpci, nullptr, &ctx->computePool);
    cpci.queueFamilyIndex = ctx->ofFamily;
    vkCreateCommandPool(ctx->device, &cpci, nullptr, &ctx->ofPool);

    // Clear the 1x1 dummies to 0 so bound-but-unused reads return defined values.
    {
        VkCommandBufferAllocateInfo ai{};
        ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
        ai.commandPool = ctx->computePool; ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY; ai.commandBufferCount = 1;
        VkCommandBuffer c; vkAllocateCommandBuffers(ctx->device, &ai, &c);
        VkCommandBufferBeginInfo bi{}; bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
        bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT; vkBeginCommandBuffer(c, &bi);
        VkClearColorValue zero{}; VkImageSubresourceRange rng{VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
        for (nvofg::Image* im : {&ctx->dummyR8, &ctx->dummyRG16}) {
            VkImageMemoryBarrier b{}; b.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
            b.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED; b.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
            b.srcQueueFamilyIndex = b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED; b.image = im->image;
            b.subresourceRange = rng; b.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
            vkCmdPipelineBarrier(c, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 1, &b);
            vkCmdClearColorImage(c, im->image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, &zero, 1, &rng);
            b.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL; b.newLayout = VK_IMAGE_LAYOUT_GENERAL;
            b.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT; b.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
            vkCmdPipelineBarrier(c, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, 0, 0, nullptr, 0, nullptr, 1, &b);
        }
        vkEndCommandBuffer(c);
        VkSubmitInfo si{}; si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO; si.commandBufferCount = 1; si.pCommandBuffers = &c;
        vkQueueSubmit(ctx->queue, 1, &si, VK_NULL_HANDLE); vkQueueWaitIdle(ctx->queue);
        vkFreeCommandBuffers(ctx->device, ctx->computePool, 1, &c);
    }

    ctx->pipelineReady = true;
    return NVOFG_OK;
}

void destroyPipeline(NvofgContext* ctx) {
    VkDevice d = ctx->device;
    if (!d) return;
    if (ctx->computePool) vkDestroyCommandPool(d, ctx->computePool, nullptr);
    if (ctx->ofPool) vkDestroyCommandPool(d, ctx->ofPool, nullptr);
    if (ctx->descPool) vkDestroyDescriptorPool(d, ctx->descPool, nullptr);
    for (Stage* s : {&ctx->prepStage, &ctx->refineStage, &ctx->warpStage}) {
        if (s->pipeline) vkDestroyPipeline(d, s->pipeline, nullptr);
        if (s->pipeLayout) vkDestroyPipelineLayout(d, s->pipeLayout, nullptr);
        if (s->setLayout) vkDestroyDescriptorSetLayout(d, s->setLayout, nullptr);
        if (s->module) vkDestroyShaderModule(d, s->module, nullptr);
    }
    if (ctx->linearSampler) vkDestroySampler(d, ctx->linearSampler, nullptr);
    if (ctx->session) ctx->of.destroySession(d, ctx->session, nullptr);
    for (Buffer* b : {&ctx->flowBuf, &ctx->costBuf}) {
        if (b->buffer) vkDestroyBuffer(d, b->buffer, nullptr);
        if (b->memory) vkFreeMemory(d, b->memory, nullptr);
    }
    for (Buffer* b : {&ctx->flowBwdBuf, &ctx->costBwdBuf}) {
        if (b->buffer) vkDestroyBuffer(d, b->buffer, nullptr);
        if (b->memory) vkFreeMemory(d, b->memory, nullptr);
    }
    for (Image* im : {&ctx->lumaPrev, &ctx->lumaCurr, &ctx->flowImg, &ctx->costImg,
                      &ctx->refinedFlow, &ctx->confidence, &ctx->dummyR8, &ctx->dummyRG16,
                      &ctx->flowBwdImg, &ctx->costBwdImg, &ctx->refinedFlowBwd, &ctx->occlusion,
                      &ctx->hintImg}) {
        if (im->view) vkDestroyImageView(d, im->view, nullptr);
        if (im->image) vkDestroyImage(d, im->image, nullptr);
        if (im->memory) vkFreeMemory(d, im->memory, nullptr);
    }
    ctx->pipelineReady = false;
}

}  // namespace nvofg

// ---------------------------------------------------------------------------
// Recording helpers
// ---------------------------------------------------------------------------
namespace {

void imgBarrier(VkCommandBuffer cmd, VkImage image, VkImageLayout from, VkImageLayout to,
                VkAccessFlags srcA, VkAccessFlags dstA) {
    VkImageMemoryBarrier b{};
    b.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    b.oldLayout = from; b.newLayout = to;
    b.srcQueueFamilyIndex = b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    b.image = image;
    b.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    b.srcAccessMask = srcA; b.dstAccessMask = dstA;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
                         0, 0, nullptr, 0, nullptr, 1, &b);
}

VkCommandBuffer beginCmd(NvofgContext* ctx, VkCommandPool pool) {
    VkCommandBufferAllocateInfo ai{};
    ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    ai.commandPool = pool;
    ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ai.commandBufferCount = 1;
    VkCommandBuffer cmd;
    vkAllocateCommandBuffers(ctx->device, &ai, &cmd);
    VkCommandBufferBeginInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);
    return cmd;
}

// Submit `cmd`, waiting on/ signalling timeline points.
void submitTimeline(VkQueue queue, VkCommandBuffer cmd,
                    VkSemaphore waitSem, uint64_t waitVal,
                    VkSemaphore sigSem, uint64_t sigVal) {
    vkEndCommandBuffer(cmd);
    VkSemaphore waits[2]; uint64_t waitVals[2]; VkPipelineStageFlags waitStages[2];
    uint32_t nWait = 0;
    if (waitSem) { waits[nWait] = waitSem; waitVals[nWait] = waitVal;
                   waitStages[nWait] = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT; ++nWait; }
    VkTimelineSemaphoreSubmitInfo ts{};
    ts.sType = VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO;
    ts.waitSemaphoreValueCount = nWait;
    ts.pWaitSemaphoreValues = waitVals;
    ts.signalSemaphoreValueCount = 1;
    ts.pSignalSemaphoreValues = &sigVal;
    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.pNext = &ts;
    si.waitSemaphoreCount = nWait;
    si.pWaitSemaphores = waits;
    si.pWaitDstStageMask = waitStages;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    si.signalSemaphoreCount = 1;
    si.pSignalSemaphores = &sigSem;
    vkQueueSubmit(queue, 1, &si, VK_NULL_HANDLE);
}

struct RefinePush { uint32_t width, height, gridW, gridH, gridSize, flags; float sigma; };
enum { REFINE_FLAG_COST = 1u, REFINE_FLAG_BIDIR = 2u, REFINE_FLAG_MOTION = 4u };
struct WarpPush   { uint32_t width, height; float phase; uint32_t flags; };
enum { WARP_FLAG_UI = 1u, WARP_FLAG_REACTIVE = 2u, WARP_FLAG_BIDIR = 4u };

}  // namespace

// ---------------------------------------------------------------------------
// C ABI: registration
// ---------------------------------------------------------------------------
extern "C" {

NvofgResult nvofg_register_color(NvofgContext* ctx, const NvofgImageDesc* prev,
                                 const NvofgImageDesc* curr) {
    if (!ctx || !prev || !curr) return NVOFG_INVALID_ARGUMENT;
    ctx->prevColor = {prev->image, prev->view, prev->format, prev->width, prev->height};
    ctx->currColor = {curr->image, curr->view, curr->format, curr->width, curr->height};
    ctx->haveColor = true;
    return NVOFG_OK;
}

NvofgResult nvofg_register_aux(NvofgContext* ctx, const NvofgAuxDesc* aux) {
    if (!ctx || !aux) return NVOFG_INVALID_ARGUMENT;
    auto store = [](const NvofgImageDesc* d, nvofg::RegImage& r, bool& has) {
        if (d) { r = {d->image, d->view, d->format, d->width, d->height}; has = true; }
        else   { has = false; }
    };
    bool dummy = false;
    store(aux->depth,       ctx->depth,      ctx->hasDepth);
    store(aux->motion,      ctx->motion,     ctx->hasMotion);
    store(aux->ui_mask,     ctx->uiMask,     ctx->hasUiMask);
    store(aux->reactive,    ctx->reactive,   ctx->hasReactive);
    store(aux->material_id, ctx->materialId, dummy);  // material id: plumbed, unused in M2
    return NVOFG_OK;
}

NvofgResult nvofg_register_output(NvofgContext* ctx, const NvofgImageDesc* interpolated) {
    if (!ctx || !interpolated) return NVOFG_INVALID_ARGUMENT;
    ctx->output = {interpolated->image, interpolated->view, interpolated->format,
                   interpolated->width, interpolated->height};
    ctx->haveOutput = true;
    return NVOFG_OK;
}

void nvofg_unregister_all(NvofgContext* ctx) {
    if (!ctx) return;
    if (ctx->pipelineReady) { vkDeviceWaitIdle(ctx->device); nvofg::destroyPipeline(ctx); }
    ctx->haveColor = ctx->haveOutput = false;
}

// ---------------------------------------------------------------------------
// C ABI: per-frame generation (AUTOMATIC mode)
// ---------------------------------------------------------------------------
NvofgResult nvofg_record_generate(NvofgContext* ctx, const NvofgGenerateInfo* info,
                                  NvofgFrameSync* out_sync) {
    if (!ctx || !info || !out_sync) return NVOFG_INVALID_ARGUMENT;
    if (ctx->mode != NVOFG_MODE_AUTOMATIC) {
        ctx->setError("only NVOFG_MODE_AUTOMATIC is implemented");
        return NVOFG_INVALID_ARGUMENT;
    }
    NvofgResult r = nvofg::ensurePipeline(ctx);
    if (r != NVOFG_OK) return r;

    const uint32_t W = ctx->width, H = ctx->height;
    const uint32_t gx = (W + 7) / 8, gy = (H + 7) / 8;

    // --- update descriptor sets (registered images are stable; single-shot M1) ---
    auto writeImg = [&](VkDescriptorSet set, uint32_t b, VkDescriptorType t,
                        VkImageView view, VkImageLayout layout, VkSampler samp) {
        VkDescriptorImageInfo ii{samp, view, layout};
        VkWriteDescriptorSet w{};
        w.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        w.dstSet = set; w.dstBinding = b; w.descriptorCount = 1; w.descriptorType = t;
        w.pImageInfo = &ii;
        vkUpdateDescriptorSets(ctx->device, 1, &w, 0, nullptr);
    };
    auto writeBuf = [&](VkDescriptorSet set, uint32_t b, VkBuffer buf, VkDeviceSize size) {
        VkDescriptorBufferInfo bi{buf, 0, size};
        VkWriteDescriptorSet w{};
        w.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        w.dstSet = set; w.dstBinding = b; w.descriptorCount = 1;
        w.descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER; w.pBufferInfo = &bi;
        vkUpdateDescriptorSets(ctx->device, 1, &w, 0, nullptr);
    };
    const VkImageLayout G = VK_IMAGE_LAYOUT_GENERAL;
    writeImg(ctx->prepPrevSet, 0, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, ctx->prevColor.view, G, VK_NULL_HANDLE);
    writeImg(ctx->prepPrevSet, 1, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, ctx->lumaPrev.view, G, VK_NULL_HANDLE);
    writeImg(ctx->prepCurrSet, 0, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, ctx->currColor.view, G, VK_NULL_HANDLE);
    writeImg(ctx->prepCurrSet, 1, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, ctx->lumaCurr.view, G, VK_NULL_HANDLE);
    VkBuffer bwdFlowBuf = ctx->bidir ? ctx->flowBwdBuf.buffer : ctx->flowBuf.buffer;  // placeholder if not bidir
    VkDeviceSize bwdFlowSz = ctx->bidir ? ctx->flowBwdBuf.size : ctx->flowBuf.size;
    writeBuf(ctx->refineSet, 0, ctx->flowBuf.buffer, ctx->flowBuf.size);
    writeBuf(ctx->refineSet, 1, ctx->costBuf.buffer, ctx->costBuf.size);
    writeBuf(ctx->refineSet, 2, bwdFlowBuf, bwdFlowSz);
    writeImg(ctx->refineSet, 3, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, ctx->refinedFlow.view, G, VK_NULL_HANDLE);
    writeImg(ctx->refineSet, 4, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, ctx->refinedFlowBwd.view, G, VK_NULL_HANDLE);
    writeImg(ctx->refineSet, 5, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, ctx->confidence.view, G, VK_NULL_HANDLE);
    writeImg(ctx->refineSet, 6, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, ctx->occlusion.view, G, VK_NULL_HANDLE);
    writeImg(ctx->refineSet, 7, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
             ctx->hasMotion ? ctx->motion.view : ctx->dummyRG16.view, G, VK_NULL_HANDLE);
    VkImageView bwdFlowView = ctx->bidir ? ctx->refinedFlowBwd.view : ctx->dummyRG16.view;
    VkImageView occView     = ctx->bidir ? ctx->occlusion.view      : ctx->dummyR8.view;
    VkImageView uiView       = ctx->hasUiMask   ? ctx->uiMask.view   : ctx->dummyR8.view;
    VkImageView reactiveView = ctx->hasReactive ? ctx->reactive.view : ctx->dummyR8.view;
    writeImg(ctx->warpSet, 0, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, ctx->prevColor.view, G, VK_NULL_HANDLE);
    writeImg(ctx->warpSet, 1, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, ctx->currColor.view, G, VK_NULL_HANDLE);
    writeImg(ctx->warpSet, 2, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, ctx->refinedFlow.view, G, VK_NULL_HANDLE);
    writeImg(ctx->warpSet, 3, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, bwdFlowView, G, VK_NULL_HANDLE);
    writeImg(ctx->warpSet, 4, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, ctx->confidence.view, G, VK_NULL_HANDLE);
    writeImg(ctx->warpSet, 5, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, occView, G, VK_NULL_HANDLE);
    writeImg(ctx->warpSet, 6, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, uiView, G, VK_NULL_HANDLE);
    writeImg(ctx->warpSet, 7, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, reactiveView, G, VK_NULL_HANDLE);
    { VkDescriptorImageInfo ii{ctx->linearSampler, VK_NULL_HANDLE, G};
      VkWriteDescriptorSet w{}; w.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
      w.dstSet = ctx->warpSet; w.dstBinding = 8; w.descriptorCount = 1;
      w.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLER; w.pImageInfo = &ii;
      vkUpdateDescriptorSets(ctx->device, 1, &w, 0, nullptr); }
    writeImg(ctx->warpSet, 9, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, ctx->output.view, G, VK_NULL_HANDLE);

    const uint64_t base = ctx->timelineValue;
    const uint64_t v1 = base + 1, v2 = base + 2, v3 = base + 3;

    // === Submit 1 (compute): prep luma from prev/curr color ===
    {
        VkCommandBuffer cmd = beginCmd(ctx, ctx->computePool);
        imgBarrier(cmd, ctx->prevColor.image, info->prev_layout, G, VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT);
        imgBarrier(cmd, ctx->currColor.image, info->curr_layout, G, VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT);
        imgBarrier(cmd, ctx->lumaPrev.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_SHADER_WRITE_BIT);
        imgBarrier(cmd, ctx->lumaCurr.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_SHADER_WRITE_BIT);
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, ctx->prepStage.pipeline);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, ctx->prepStage.pipeLayout,
                                0, 1, &ctx->prepPrevSet, 0, nullptr);
        vkCmdDispatch(cmd, gx, gy, 1);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, ctx->prepStage.pipeLayout,
                                0, 1, &ctx->prepCurrSet, 0, nullptr);
        vkCmdDispatch(cmd, gx, gy, 1);
        submitTimeline(ctx->queue, cmd, info->input_timeline, info->input_value, ctx->timeline, v1);
    }

    // === Submit 2 (optical flow): execute forward flow + cost ===
    {
        VkCommandBuffer cmd = beginCmd(ctx, ctx->ofPool);
        imgBarrier(cmd, ctx->flowImg.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_MEMORY_WRITE_BIT);
        imgBarrier(cmd, ctx->costImg.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_MEMORY_WRITE_BIT);
        if (ctx->bidir) {
            imgBarrier(cmd, ctx->flowBwdImg.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_MEMORY_WRITE_BIT);
            imgBarrier(cmd, ctx->costBwdImg.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_MEMORY_WRITE_BIT);
        }
        VkOpticalFlowExecuteInfoNV ei{};
        ei.sType = VK_STRUCTURE_TYPE_OPTICAL_FLOW_EXECUTE_INFO_NV;
        ei.flags = VK_OPTICAL_FLOW_EXECUTE_DISABLE_TEMPORAL_HINTS_BIT_NV;
        ctx->of.cmdExecute(cmd, ctx->session, &ei);
        submitTimeline(ctx->ofQueue, cmd, ctx->timeline, v1, ctx->timeline, v2);
    }

    // === Submit 3 (compute): copy flow/cost -> buffers, refine, warp -> output ===
    {
        VkCommandBuffer cmd = beginCmd(ctx, ctx->computePool);
        imgBarrier(cmd, ctx->flowImg.image, G, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT);
        imgBarrier(cmd, ctx->costImg.image, G, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT);
        VkBufferImageCopy fc{}; fc.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
        fc.imageExtent = {ctx->gridW, ctx->gridH, 1};
        vkCmdCopyImageToBuffer(cmd, ctx->flowImg.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, ctx->flowBuf.buffer, 1, &fc);
        vkCmdCopyImageToBuffer(cmd, ctx->costImg.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, ctx->costBuf.buffer, 1, &fc);
        if (ctx->bidir) {
            imgBarrier(cmd, ctx->flowBwdImg.image, G, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT);
            imgBarrier(cmd, ctx->costBwdImg.image, G, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT);
            vkCmdCopyImageToBuffer(cmd, ctx->flowBwdImg.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, ctx->flowBwdBuf.buffer, 1, &fc);
            vkCmdCopyImageToBuffer(cmd, ctx->costBwdImg.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, ctx->costBwdBuf.buffer, 1, &fc);
        }
        VkMemoryBarrier mb{VK_STRUCTURE_TYPE_MEMORY_BARRIER, nullptr, VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT};
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);

        imgBarrier(cmd, ctx->refinedFlow.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_SHADER_WRITE_BIT);
        imgBarrier(cmd, ctx->refinedFlowBwd.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_SHADER_WRITE_BIT);
        imgBarrier(cmd, ctx->confidence.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_SHADER_WRITE_BIT);
        imgBarrier(cmd, ctx->occlusion.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_SHADER_WRITE_BIT);
        uint32_t rflags = REFINE_FLAG_COST | (ctx->bidir ? REFINE_FLAG_BIDIR : 0u)
                        | (ctx->hasMotion ? REFINE_FLAG_MOTION : 0u);
        RefinePush rp{W, H, ctx->gridW, ctx->gridH, ctx->gridSize, rflags,
                      (ctx->quality == NVOFG_QUALITY_HIGH) ? 32.f : 48.f};
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, ctx->refineStage.pipeline);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, ctx->refineStage.pipeLayout, 0, 1, &ctx->refineSet, 0, nullptr);
        vkCmdPushConstants(cmd, ctx->refineStage.pipeLayout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(rp), &rp);
        vkCmdDispatch(cmd, gx, gy, 1);

        VkMemoryBarrier mb2{VK_STRUCTURE_TYPE_MEMORY_BARRIER, nullptr, VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT};
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb2, 0, nullptr, 0, nullptr);
        imgBarrier(cmd, ctx->refinedFlow.image, G, G, VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT);
        imgBarrier(cmd, ctx->refinedFlowBwd.image, G, G, VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT);
        imgBarrier(cmd, ctx->confidence.image, G, G, VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT);
        imgBarrier(cmd, ctx->occlusion.image, G, G, VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT);
        imgBarrier(cmd, ctx->output.image, VK_IMAGE_LAYOUT_UNDEFINED, G, 0, VK_ACCESS_SHADER_WRITE_BIT);
        uint32_t wflags = 0;
        if (ctx->hasUiMask)   wflags |= WARP_FLAG_UI;
        if (ctx->hasReactive) wflags |= WARP_FLAG_REACTIVE;
        if (ctx->bidir)       wflags |= WARP_FLAG_BIDIR;
        WarpPush wp{W, H, info->phase, wflags};
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, ctx->warpStage.pipeline);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, ctx->warpStage.pipeLayout, 0, 1, &ctx->warpSet, 0, nullptr);
        vkCmdPushConstants(cmd, ctx->warpStage.pipeLayout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(wp), &wp);
        vkCmdDispatch(cmd, gx, gy, 1);
        submitTimeline(ctx->queue, cmd, ctx->timeline, v2, ctx->timeline, v3);
    }

    ctx->timelineValue = v3;
    out_sync->semaphore = ctx->timeline;
    out_sync->value = v3;
    return NVOFG_OK;
}

}  // extern "C"
